### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [manaruchi/SPIUtility#1]
# Problem

Please add a proper homepage 

![Screenshot 2019-10-05 at 09 06 30](https://user-images.githubusercontent.com/2510900/66251349-756cad80-e74f-11e9-8ce1-a616fec14980.png)

Also remove the .pyc files as they are generated automatically on install

**Comment by manaruchi** [comment]
Thank you for reporting the issue. The issue has been resolved.
